### ISSUE TITLE
Pipelines Jenkins ?

### ISSUE THREAD

**Issue by bertrandbo** [francoistonic/programmez242#1]
Bonjour !

Sauf erreur de ma part, il manque le code de l'article sur les Pipelines Jenkins. Pouvez-vous l'ajouter dans le dépôt svp ?

Bonne journée

**Comment by francoistonic** [comment]
bonjour,

oups. dossier à jour. désolé pour cet oubli

**Comment by bertrandbo** [comment]
Merci beaucoup !
